
[module]

[[module.imports]]
path="github.com/refactoringui/heroicons"
[[module.imports.mounts]]
source = "src"
target = "assets/emoji/heroicons"

[[module.imports]]
path="github.com/twitter/twemoji"
[[module.imports.mounts]]
source = "assets/svg"
target = "assets/emoji/twitter"
